### PR TITLE
Prevent updating plugins which are not installed.

### LINKED ISSUE #442: Updating plugins that aren't installed
A little more defensive coding might be needed to check the plugin is actually installed before trying to bulk update it. The plugin does actually get installed.

```
The update process is starting. This process may take a while on some hosts, so please be patient.

Backtrace from warning 'fopen(/srv/www/wordpress-develop/src/wp-content/plugins/genesis-accessible) [function.fopen.php]: failed to open stream: No such file or directory' at /srv/www/wordpress-develop/src/wp-includes/functions.php 4304:

/srv/www/wordpress-develop/src/wp-includes/functions.php 4304 calling fopen()
/srv/www/wordpress-develop/src/wp-admin/includes/plugin.php 88 calling get_file_data()
/srv/www/wordpress-develop/src/wp-admin/includes/class-wp-upgrader.php 963 calling get_plugin_data()
/srv/www/wordpress-develop/src/wp-content/themes/utility-pro/includes/vendors/tgm-plugin-activation/class-tgm-plugin-activation.php 3148 calling bulk_upgrade()
/srv/www/wordpress-develop/src/wp-content/themes/utility-pro/includes/vendors/tgm-plugin-activation/class-tgm-plugin-activation.php 2723 calling bulk_upgrade()
/srv/www/wordpress-develop/src/wp-content/themes/utility-pro/includes/vendors/tgm-plugin-activation/class-tgm-plugin-activation.php 629 calling process_bulk_actions()
calling install_plugins_page()
/srv/www/wordpress-develop/src/wp-includes/plugin.php 503 calling call_user_func_array()
/srv/www/wordpress-develop/src/wp-admin/admin.php 236 calling do_action()
/srv/www/wordpress-develop/src/wp-admin/themes.php 10 calling require_once()
Backtrace from warning 'fread() expects parameter 1 to be resource, boolean given' at /srv/www/wordpress-develop/src/wp-includes/functions.php 4307:

/srv/www/wordpress-develop/src/wp-includes/functions.php 4307 calling fread()
/srv/www/wordpress-develop/src/wp-admin/includes/plugin.php 88 calling get_file_data()
/srv/www/wordpress-develop/src/wp-admin/includes/class-wp-upgrader.php 963 calling get_plugin_data()
/srv/www/wordpress-develop/src/wp-content/themes/utility-pro/includes/vendors/tgm-plugin-activation/class-tgm-plugin-activation.php 3148 calling bulk_upgrade()
/srv/www/wordpress-develop/src/wp-content/themes/utility-pro/includes/vendors/tgm-plugin-activation/class-tgm-plugin-activation.php 2723 calling bulk_upgrade()
/srv/www/wordpress-develop/src/wp-content/themes/utility-pro/includes/vendors/tgm-plugin-activation/class-tgm-plugin-activation.php 629 calling process_bulk_actions()
calling install_plugins_page()
/srv/www/wordpress-develop/src/wp-includes/plugin.php 503 calling call_user_func_array()
/srv/www/wordpress-develop/src/wp-admin/admin.php 236 calling do_action()
/srv/www/wordpress-develop/src/wp-admin/themes.php 10 calling require_once()
Backtrace from warning 'fclose() expects parameter 1 to be resource, boolean given' at /srv/www/wordpress-develop/src/wp-includes/functions.php 4310:

/srv/www/wordpress-develop/src/wp-includes/functions.php 4310 calling fclose()
/srv/www/wordpress-develop/src/wp-admin/includes/plugin.php 88 calling get_file_data()
/srv/www/wordpress-develop/src/wp-admin/includes/class-wp-upgrader.php 963 calling get_plugin_data()
/srv/www/wordpress-develop/src/wp-content/themes/utility-pro/includes/vendors/tgm-plugin-activation/class-tgm-plugin-activation.php 3148 calling bulk_upgrade()
/srv/www/wordpress-develop/src/wp-content/themes/utility-pro/includes/vendors/tgm-plugin-activation/class-tgm-plugin-activation.php 2723 calling bulk_upgrade()
/srv/www/wordpress-develop/src/wp-content/themes/utility-pro/includes/vendors/tgm-plugin-activation/class-tgm-plugin-activation.php 629 calling process_bulk_actions()
calling install_plugins_page()
/srv/www/wordpress-develop/src/wp-includes/plugin.php 503 calling call_user_func_array()
/srv/www/wordpress-develop/src/wp-admin/admin.php 236 calling do_action()
/srv/www/wordpress-develop/src/wp-admin/themes.php 10 calling require_once()
Updating Plugin Genesis Accessible (1/3)
Genesis Accessible updated successfully. Show Details
~~~

### PR DESCRIPTION
**Pull request by jrfnl**
Fixes #442

### CODE REVIEW

File: class-tgm-plugin-activation.php [hunk 1]
```diff
@@ -2675,7 +2675,7 @@ public function process_bulk_actions() {
 					}
 
 					// For updates: make sure this is a plugin we *can* update (update available and WP version ok).
-					if ( 'update' === $install_type && ( $this->tgmpa->is_plugin_installed( $slug ) && ( false === $this->tgmpa->does_plugin_have_update( $slug ) || ! $this->tgmpa->can_plugin_update( $slug ) ) ) ) {
+					if ( 'update' === $install_type && ( ! $this->tgmpa->is_plugin_installed( $slug ) || ( $this->tgmpa->is_plugin_installed( $slug ) && ( false === $this->tgmpa->does_plugin_have_update( $slug ) || ! $this->tgmpa->can_plugin_update( $slug ) ) ) ) ) {
```
Comment (GaryJones) [inline class-tgm-plugin-activation.php]: This set of conditions is too long. It's not easy to read or understand. Please extract into a new documented method.

Comment (jrfnl) [inline class-tgm-plugin-activation.php]: Agreed. Updated, rebased & squashed.
