### PR TITLE
Fix URLs in custom Menus

### LINKED ISSUE #412: Begin installing plugins - 404
I am testing v2.5 and I am getting 404 when click on "Begin Installing Plugins".
I changed "parent_slug" value to custom value: "pixely_options" (I want to move "Install plugins" under my custom Menu) and now URL for installing plugins is wrong:

http://localhost/wordpress-latest/wp-admin/pixely_options?page=install-required-plugins&plugin_status=install

In previous versions there was "parent_url_slug" parameter that now seems not to be available and instead of it "parent_slug" is used.

I am doing something wrong or this is bug?

Vladimir

### PR DESCRIPTION
**Pull request by jrfnl**
Fixes #412

### CODE REVIEW

File: class-tgm-plugin-activation.php [hunk 1]
```diff
@@ -1630,11 +1630,15 @@ public function get_tgmpa_url() {
 			static $url;
 
 			if ( ! isset( $url ) ) {
+				$parent = $this->parent_slug;
+				if ( strpos( $parent, '.php' ) === false ) {
```
Comment (GaryJones) [inline class-tgm-plugin-activation.php]: Yoda condition please.

Comment (jrfnl) [inline class-tgm-plugin-activation.php]: You'll just have to keep telling me that again and again... I just can't get used to it. Anyways, fixed & squashed.
